[project]
name = "game_agent"
version = "0.1.0"
description = "Pong and ALE Stuff"
readme = "./game_agent/README.md"
requires-python = ">=3.10"
dependencies = [
    "ale-py>=0.11.2",
    "gymnasium[box2d]>=1.2.3",
    "opencv-python>=4.13.0.92",
    "pygame>=2.6.1",
    "swig>=4.4.1",
]

[build-system]
requires = ["uv>=0.1.0", "uv_build>=0.11.9,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "game_agent"
module-root = "."
