[project]
name = "llm_do"
version = "0.1.0"
description = "Random LLM API Stuff"
readme = "./llm_do/README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.5",
    "uv_build>=0.11.9,<0.12"
]

[build-system]
requires = ["uv>=0.1.0", "uv_build>=0.11.9,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "llm_do"
module-root = "."
